### PR TITLE
bump clang format version to 18.0.0

### PR DESCRIPTION
**Pull request by linusboehm**
shas from: [here](https://chromium.googlesource.com/chromium/src/+/17e361b25633686d56dce7c2b59d99ac13fcc74c/buildtools)

### CODE REVIEW

**Review by jlebar — APPROVED** [review]
Thanks!

**Comment by jlebar** [comment]
FTR I verified the SHAs against the link you gave.  (Doing my part to hopefully avoid supply-chain attacks.)

**Comment by linusboehm** [comment]
thanks for approving it so quickly! I can't merge it in (no write access), but feel free to merge when convenient.

**Comment by jlebar** [comment]
Oh right.  :)  Thanks, merged.

**Pull request merged**
